evently/Pages/Admin/Index.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;
using System.Text;
using System.Text.Encodings.Web;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Primitives;
using PostmarkDotNet.Exceptions;
using evently.Models;

namespace evently.Pages.Admin;

[Authorize(Roles = "Admin")]
public class Index : PageModel
{
    public List<User> Users { get; set; } = new List<User>();
    public List<Event> Events { get; set; } = new List<Event>();
    public List<Contact> Contacts { get; set; } = new List<Contact>();
    
    public readonly EventAppDbContext _db;
    private readonly UserManager<User> _userManager;
    private readonly IEmailSender _emailSender;
    private readonly IUserStore<User> _userStore;
    private readonly SignInManager<User> _signInManager;

    public string? EventSearchQuery;
    public string? UserSearchQuery;
    public string? ContactSearchQuery;

    // public ForgotPasswordModel(UserManager<User> userManager, IEmailSender emailSender)
    
    public Index(EventAppDbContext db, UserManager<User> userManager, IEmailSender emailSender, IUserStore<User> userStore, SignInManager<User> signInManager)
    {
        this._db = db;
        _userManager = userManager;
        _emailSender = emailSender;
        _userStore = userStore;
        _signInManager = signInManager;
    }
    
    public void OnGetAsync()
    {
        EventSearchQuery = Request.Query["EventSearchQuery"];
        UserSearchQuery = Request.Query["UserSearchQuery"];
        ContactSearchQuery = Request.Query["ContactSearchQuery"];
    }
    
    public async Task<IActionResult> OnPostDeleteUserAsync(string id, string previousSearchQuery, string previousEventSearchQuery, string previousContactSearchQuery)
    {
        string currentUserId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value ?? "";
        
        if(currentUserId == "")
        {
            TempData["BannerMessage"] = "Deletion not successful: Could not perform validation check.";
            return RedirectToPage(new { UserSearchQuery = previousSearchQuery, EventSearchQuery = previousEventSearchQuery, ContactSearchQuery = previousContactSearchQuery });
        }
        
        if (currentUserId == id)
        {
            TempData["BannerMessage"] = "Deletion not successful: You cannot delete yourself.";
            return RedirectToPage(new { UserSearchQuery = previousSearchQuery, EventSearchQuery = previousEventSearchQuery, ContactSearchQuery = previousContactSearchQuery });
        }
        
        var user = await _db.Users.FindAsync(id);
        if (user == null)
        {
            TempData["BannerMessage"] = "Deletion not successful: User not found.";
            return RedirectToPage(new { UserSearchQuery = previousSearchQuery, EventSearchQuery = previousEventSearchQuery, ContactSearchQuery = previousContactSearchQuery });
        }

        _db.Users.Remove(user);
        await _db.SaveChangesAsync();
        
        TempData["BannerMessage"] = "User deleted successfully";
        return RedirectToPage(new { UserSearchQuery = previousSearchQuery, EventSearchQuery = previousEventSearchQuery, ContactSearchQuery = previousContactSearchQuery }); // This will redirect to the same page with the same search query in the URL
    }
    
    public async Task<IActionResult> OnPostResetPasswordAsync(string id, string previousSearchQuery, string previousEventSearchQuery, string previousContactSearchQuery)
    {
        var user = await _db.Users.FindAsync(id);
        if (user == null)
        {
            TempData["BannerMessage"] = "Password reset NOT sent; user not found.";
            return RedirectToPage(new { UserSearchQuery = previousSearchQuery, EventSearchQuery = previousEventSearchQuery, ContactSearchQuery = previousContactSearchQuery });
        }
        if (user.Email == null)
        {
            TempData["BannerMessage"] = "Password reset NOT sent; user has no set email.";
            return RedirectToPage(new { UserSearchQuery = previousSearchQuery, EventSearchQuery = previousEventSearchQuery, ContactSearchQuery = previousContactSearchQuery });
        }
        
        // Consider checking for email confirmation here. If not confirmed, don't send the email.
        
        String currentUserFirstName = _db.Users.Find(User.FindFirst(ClaimTypes.NameIdentifier)?.Value)?.FirstName ?? "Admin";
        
        var code = await _userManager.GeneratePasswordResetTokenAsync(user);
        code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
        var callbackUrl = Url.Page(
            "/Account/ResetPassword",
            pageHandler: null,
            values: new { area = "Identity", code },
            protocol: Request.Scheme);
        
        // Grab the email template from ./EmailTemplates/AdminRequestedPasswordReset.html:
        string emailTemplate = System.IO.File.ReadAllText("./EmailTemplates/AdminRequestedPasswordReset.html");
        emailTemplate = emailTemplate.Replace("{{firstName}}", user.FirstName);
        emailTemplate = emailTemplate.Replace("{{resetLink}}", callbackUrl);
        emailTemplate = emailTemplate.Replace("{{signedBy}}", currentUserFirstName);

        await _emailSender.SendEmailAsync(
            user.Email,
            "Reset Password",
            emailTemplate);
        
        TempData["BannerMessage"] = "Sent password reset email to " + user.Email;
        // This will redirect to the same page with the same search query in the URL
        return RedirectToPage(new { UserSearchQuery = previousSearchQuery, EventSearchQuery = previousEventSearchQuery, ContactSearchQuery = previousContactSearchQuery });
    }

    // Handles all user updates that require hitting the save button (ones that might be more sensitive)
    public async Task<IActionResult> OnPostSaveUserAsync(string id, string role, string username, string email, string previousSearchQuery, string previousEventSearchQuery, string previousContactSearchQuery)
    {
        var user = await _db.Users.FindAsync(id);
        var thisUserId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

        bool changesMade = false;
        
        if (user == null)
        {
            TempData["BannerMessage"] = "User not found. Could not save changes.";
            return RedirectToPage(new { UserSearchQuery = previousSearchQuery, EventSearchQuery = previousEventSearchQuery, ContactSearchQuery = previousContactSearchQuery }); // This will redirect to the same page with the same search query in the URL
        }
        
        
        // ROLE CHANGES BEGIN //
        if(role == "user") role = "visitor";
        if(role != "visitor" && role != "admin")
        {
            TempData["BannerMessage"] = "Invalid role. Could not save changes.";
            return RedirectToPage(new { UserSearchQuery = previousSearchQuery, EventSearchQuery = previousEventSearchQuery, ContactSearchQuery = previousContactSearchQuery });
        }
        if (!_userManager.IsInRoleAsync(user, role).Result)
        {
            if (user.Id == thisUserId)
            {
                TempData["BannerMessage"] = "You cannot change your own role.";
                return RedirectToPage(new { UserSearchQuery = previousSearchQuery, EventSearchQuery = previousEventSearchQuery, ContactSearchQuery = previousContactSearchQuery });
            }
            
            // Remove them from the other role
            await _userManager.RemoveFromRoleAsync(user, role == "admin" ? "visitor" : "admin");
            
            // Add them to the new role
            await _userManager.AddToRoleAsync(user, role);
            
            // Might need to sign the user out
            
            // Used for the UI message
            changesMade = true;
        }
        // ROLE CHANGES END //
        
        // USERNAME CHANGES BEGIN //
        if(user.NormalizedUserName != username.ToUpper())
        {
            // Check if a user already exists with the new username
            var userWithNewUsername = await _userManager.FindByNameAsync(username);
            if (userWithNewUsername != null)
            {
                TempData["BannerMessage"] = "Username already taken. Could not save changes.";
                return RedirectToPage(new { UserSearchQuery = previousSearchQuery, EventSearchQuery = previousEventSearchQuery, ContactSearchQuery = previousContactSearchQuery });
            }
            
            await _userManager.SetUserNameAsync(user, username);
            
            changesMade = true;
        }
        // USERNAME CHANGES END //
        
        // EMAIL CHANGES BEGIN //
        if(user.NormalizedEmail != email.ToUpper())
        {
            // Check if a user already exists with the new email
            var userWithNewEmail = await _userManager.FindByEmailAsync(email);
            if (userWithNewEmail != null)
            {
                TempData["BannerMessage"] = "Email already taken. Could not save changes.";
                return RedirectToPage(new { UserSearchQuery = previousSearchQuery, EventSearchQuery = previousEventSearchQuery, ContactSearchQuery = previousContactSearchQuery });
            }

            // Inform them of the change via their old email
            if (user.Email != null)
            {
                string emailTemplate = System.IO.File.ReadAllText("./EmailTemplates/EmailChange.html");
                emailTemplate = emailTemplate.Replace("{{firstName}}", user.FirstName);
                emailTemplate = emailTemplate.Replace("{{newEmail}}", email);
                try
                {
                    await _emailSender.SendEmailAsync(user.Email, "Email Change Confirmation", emailTemplate);
                }

evently/Pages/Admin/Index.cshtml
@page
@using Microsoft.AspNetCore.Identity
@using evently.Models
@using System.Security.Claims
@model evently.Pages.Admin.Index

@inject UserManager<User> UserManager;

@{
  ViewData["Title"] = "Admin Panel";
}

@section Styles {
  <link rel="stylesheet" href="~/css/admin/index.css" asp-append-version="true" />
}

<h1 style="margin-bottom: 0.1em">Admin page</h1>
<h3 style="margin-top: 0">View general and per-event analytics</h3>

<partial name="_EventList"/>
<partial name="_UserList"/>
<partial name="_ContactList"/>



@* This script is responsible for updating the hidden inputs in the save-changes-form *@
@* and enabling the save button when the user changes a property on a given user *@
@section Scripts {
  <script>
    $(() => {      
      
      $("tr").each((i, tr) => {
        // check if the tr has an id attribute
        if (!$(tr).attr("id")) {
          return;
        }
        
        const saveChangesForm = $(tr).find("#save-changes-form");
        const id = $(tr).attr("id");
        const usernameInput = $(tr).find(".username-input");
        const emailInput = $(tr).find(".email-input");
        const roleSelector = $(tr).find(".role-selector");
        
        
        usernameInput.val(usernameInput.attr("placeholder"));
        usernameInput.on("input", (e) => {
          saveChangesForm.find("input[name='username']").val($(e.target).val());
          saveChangesForm.find("button").removeAttr("disabled");
        });
        
        emailInput.val(emailInput.attr("placeholder"));
        emailInput.on("input", (e) => {
          saveChangesForm.find("input[name='email']").val($(e.target).val());
          saveChangesForm.find("button").removeAttr("disabled");
        });
        
        roleSelector.on("change", (e) => {
          saveChangesForm.find("input[name='role']").val($(e.target).val());
          saveChangesForm.find("button").removeAttr("disabled");
        });
      });
      
      $(".open-contact-button").on("click", (e) => {
        const name = $(e.target).attr("name");
        const email = $(e.target).attr("email");
        const phone = $(e.target).attr("phone");
        const event = $(e.target).attr("event");
        const host = $(e.target).attr("host");
        const message = $(e.target).attr("message");
        openMessagePopup(name, email, phone, event, host, message);
      });
      
      $(".close-popup").on("click", (e) => {
        $(".popup").fadeOut(200);
      });
      
      console.log("Admin page scripts loaded");
      function openMessagePopup(name, email, phone, event, host, message) {
        $(".popup .icon-container span:nth-child(1)").html(`<span class="material-symbols-outlined">person</span> ${name || "N/A"}`);
        $(".popup .icon-container span:nth-child(2)").html(`<span class="material-symbols-outlined">email</span> ${email || "N/A"}`);
        $(".popup .icon-container span:nth-child(3)").html(`<span class="material-symbols-outlined">phone</span> ${phone || "N/A"}`);
        $(".popup .icon-container span:nth-child(4)").html(`<span class="material-symbols-outlined">event</span> ${event || "N/A"}`);
        $(".popup .icon-container span:nth-child(5)").html(`<span class="material-symbols-outlined">corporate_fare</span> ${host || "N/A"}`);
        
        $(".popup .message").val(message || "Cannot find message. Please try again.");
        
        const popup = $(".popup");
        $(popup).css("display", "flex");
        $(popup).hide().fadeIn(200);
        
      }
      
    });
  </script>
}

evently/Pages/Admin/_ContactList.cshtml
@model Admin.Index


@{
  // Contact Search
  if (string.IsNullOrEmpty(Model.ContactSearchQuery) || !Model.ModelState.IsValid)
  {
    Model.Contacts = Model._db.Contacts.ToList();
    TempData["ContactStatusMessage"] = "Showing all contact form submissions.";
  }
  else
  {
    Model.ContactSearchQuery = Model.ContactSearchQuery.ToLower();
    Model.Contacts = Model._db.Contacts.Where(c =>
      (c.FirstName + " " + c.LastName).ToLower().Contains(Model.ContactSearchQuery) ||
      c.Email.ToLower().Contains(Model.ContactSearchQuery) ||
      c.Phone != null && c.Phone.ToLower().Contains(Model.ContactSearchQuery)
    ).ToList();

    TempData["ContactStatusMessage"] =
      $"Showing contact form submissions with name, email, or phone number containing '{Model.ContactSearchQuery}'.";
  }
}

<div class="popup">
  <h2>Message</h2>
  <p class="icon-container">
    <span><span class="material-symbols-outlined">person</span>N/A</span>
    <span><span class="material-symbols-outlined">email</span>N/A</span>
    <span><span class="material-symbols-outlined">phone</span>N/A</span>
    <span><span class="material-symbols-outlined">event</span>N/A</span>
    <span><span class="material-symbols-outlined">corporate_fare</span>N/A</span>
  </p>
  <textarea class="message" readonly>This is a message from a user</textarea>
  <button class="solid close-popup" style="margin-top: 1em; max-width: 10em">CLOSE</button>
</div>

<div>
  <h2>Contact Us Submissions</h2>
  <form method="get" class="admin-search-form">
    <input type="text" id="search" placeholder="Search for submissions.." asp-for="ContactSearchQuery">
    <input type="hidden" name="UserSearchQuery" value="@Model.UserSearchQuery" />
    <input type="hidden" name="EventSearchQuery" value="@Model.EventSearchQuery" />
    <button type="submit" class="material-symbols-outlined">search</button>
  </form>
  
  <span class="status-message">@TempData["ContactStatusMessage"]</span>
  
  <div class="table-container">
    <table>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Event</th>
        <th>Event Host</th>
        <th class="center">View</th>
      </tr>
      @foreach(var _contact in Model.Contacts)
      {
        <tr id="@_contact.Id">
          <td>@_contact.Id</td>
          <td>@(_contact.FirstName + " " + _contact.LastName)</td>
          <td>@_contact.Email</td>
          <td>@(_contact.Phone ?? "N/A")</td>
          <td>@(_contact.EventName ?? "N/A")</td>
          <td>@(_contact.EventHost ?? "N/A")</td>

          <td class="center">
            <button class="material-symbols-outlined hidden open-contact-button" 
                    name="@_contact.FirstName @_contact.LastName"
                    email="@_contact.Email"
                    phone="@_contact.Phone"
                    event="@_contact.EventName"
                    host="@_contact.EventHost"
                    message="@_contact.Message"
            >open_in_full</button>
          </td>
        </tr>
      }
    </table>
  </div>
</div>

evently/Pages/Admin/_EventList.cshtml
@model Pages.Admin.Index


@{
  // Event Search
  if (string.IsNullOrEmpty(Model.EventSearchQuery) || !Model.ModelState.IsValid)
  {
    Model.Events = Model._db.Events.OrderByDescending(e => e.DateTime).Take(50).ToList();
    TempData["EventStatusMessage"] = "Showing the first 50 events, sorted by date occurring.";
  }
  else
  {
    Model.EventSearchQuery = Model.EventSearchQuery.ToLower();
    Model.Events = Model._db.Events.OrderByDescending(e => e.DateTime).Where(e =>
      (e.Name.ToLower().Contains(Model.EventSearchQuery)) ||
      (Model._db.Users.FirstOrDefault(u => u.Id == e.HostId) != null && 
       Model._db.Users.First(u => u.Id == e.HostId).UserName.ToLower().Contains(Model.EventSearchQuery))
    ).ToList();

    TempData["EventStatusMessage"] =
      $"Showing events with name or host name containing '{Model.EventSearchQuery}', sorted by date occurring.";
  }
}

<div>
  <div style="display: flex; flex-direction: row; align-items: center; justify-content: space-between">
    <h2>Events</h2>
    
    <form method="get" asp-page="/Events/Edit">
      <button type="submit" class="solid">+</button>
    </form>
  </div>
  <form method="get" class="admin-search-form">
    <input type="text" id="search" placeholder="Search for events.." asp-for="EventSearchQuery">
    <input type="hidden" name="UserSearchQuery" value="@Model.UserSearchQuery" />
    <input type="hidden" name="ContactSearchQuery" value="@Model.ContactSearchQuery" />
    <button type="submit" class="material-symbols-outlined">search</button>
  </form>
  
  <span class="status-message">@TempData["EventStatusMessage"]</span>
  
  <div class="table-container">
    <table>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Organiser</th>
        <th>Seats</th>
        <th>Occupancy</th>
        <th>Fill %</th>
        <th class="center">Status</th>
        <th class="center">Edit</th>
        <th class="center">Delete</th>
      </tr>
      @foreach(var _event in Model.Events)
      {
        <tr id="@_event.Id" class="@(_event.DateTime > DateTime.Now ? "" : "expired")">
          <td class="id-field">@_event.Id</td>
          <td>@_event.Name <a target="_blank" href="/Events/view/@_event.Id" class="material-symbols-outlined sml">open_in_new</a></td>
          <td>@(Model._db.Users.FirstOrDefault(u => u.Id == _event.HostId)?.UserName ?? "N/A")</td>
          <td>@_event.Capacity</td>
          <td>@_event.Registered</td>
          <td>@(_event.Capacity > 0 ? Math.Round((double)_event.Registered / _event.Capacity * 100, 2) : 100)%</td>
  
          <td class="center status">@(_event.DateTime > DateTime.Now ? "Upcoming" : "Past")</td>
          <td class="center">
            <a href="/Events/Edit/@_event.Id" class="material-symbols-outlined">edit</a>
          </td>
          <td class="center">
            <form method="post" asp-page-handler="DeleteEvent">
              <input type="hidden" name="id" value="@_event.Id"/>
              <input type="hidden" name="previousEventSearchQuery" value="@Model.EventSearchQuery" />
              <input type="hidden" name="previousSearchQuery" value="@Model.UserSearchQuery" />
              <input type="hidden" name="previousContactSearchQuery" value="@Model.ContactSearchQuery" />
              <button type="submit" class="material-symbols-outlined hidden">delete</button>
            </form>
          </td>
        </tr>
      }
    </table>
  </div>
</div>

evently/Pages/Admin/_UserList.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using evently.Models
@using System.Security.Claims
@model evently.Pages.Admin.Index

@inject UserManager<User> UserManager;

@{
  // User Search
  if (string.IsNullOrEmpty(Model.UserSearchQuery) || !Model.ModelState.IsValid)
  {
    Model.Users = Model._db.Users.OrderByDescending(u => u.CreationDate).Take(50).ToList();
    TempData["StatusMessage"] = "Showing the first 50 users, sorted by creation date.";
  }
  else
  {
    Model.UserSearchQuery = Model.UserSearchQuery.ToLower();
    // Console.WriteLine($"Searching for users with email or name containing '{UserSearchQuery}'");
    Model.Users = Model._db.Users.OrderByDescending(u => u.CreationDate).Where(u =>
      (u.Email != null && u.Email.ToLower().Contains(Model.UserSearchQuery)) ||
      (u.UserName != null && (u.UserName).ToLower().Contains(Model.UserSearchQuery))
    ).ToList();

    TempData["StatusMessage"] =
      $"Showing users with email or name containing '{Model.UserSearchQuery}', sorted by creation date.";
  }
}


<div>
  <h2>Users</h2>
  <form method="get" class="admin-search-form">
    <input type="text" id="search" placeholder="Search for names.." asp-for="UserSearchQuery">
    <input type="hidden" name="EventSearchQuery" value="@Model.EventSearchQuery" />
    <input type="hidden" name="ContactSearchQuery" value="@Model.ContactSearchQuery" />
    <button type="submit" class="material-symbols-outlined">search</button>
  </form>
  
  <span class="status-message">@TempData["StatusMessage"]</span>
  
  <div class="table-container">
    <table>
      <tr>
        <th>ID</th>
        <th>
          Username
          <span class="material-symbols-outlined sml" style="margin-left: 4px">edit</span>
        </th>
        <th>
          Email
          <span class="material-symbols-outlined sml" style="margin-left: 4px">edit</span>
        </th>
        <th>Role</th>
        <th>Joined</th>
        <th class="center">Password</th>
        <th class="center">Bookings</th>
        <th class="center">Delete</th>
        <th class="center">Save</th>
      </tr>
      @foreach(var user in Model.Users)
      {
        <tr id="@user.Id">
          <td class="id-field">@user.Id</td>
          <td class="username-input-container" id="@user.Id">
            <input class="username-input" placeholder="@user.UserName" />
          </td>
          <td class="email-input-container" id="@user.Email">
            <input class="email-input" placeholder="@user.Email" />
          </td>
    
          <td>
            <select class="role-selector">
              @if (UserManager.IsInRoleAsync(user, "Admin").Result)
              {
                <option value="admin" selected>Admin</option>
                <option value="user">User</option>
              }
              else
              {
                <option value="admin">Admin</option>
                <option value="user" selected>User</option>
              }
            </select>
          </td>
    
          <td>@user.CreationDate</td>
          <td class="center">
            <form method="post" asp-page-handler="ResetPassword" id="test">
              <input type="hidden" name="id" value="@user.Id" />
              <input type="hidden" name="previousSearchQuery" value="@Model.UserSearchQuery" />
              <input type="hidden" name="previousEventSearchQuery" value="@Model.EventSearchQuery" />
              <input type="hidden" name="previousContactSearchQuery" value="@Model.ContactSearchQuery" />
              <button type="submit" class="material-symbols-outlined hidden">lock_reset</button>
            </form>
          </td>
          
          <td class="center">
            <a href="/Identity/Account/Manage/Bookings/@user.Id" class="material-symbols-outlined">calendar_today</a>
          </td>
    
          <td class="center">
            <form method="post" asp-page-handler="DeleteUser">
              <input type="hidden" name="id" value="@user.Id"/>
              <input type="hidden" name="previousSearchQuery" value="@Model.UserSearchQuery" />
              <input type="hidden" name="previousEventSearchQuery" value="@Model.EventSearchQuery" />
              <input type="hidden" name="previousContactSearchQuery" value="@Model.ContactSearchQuery" />
              <button type="submit" class="material-symbols-outlined hidden @(User.FindFirst(ClaimTypes.NameIdentifier)?.Value == user.Id ? "fake-disabled" : "")" >delete</button>
            </form>
          </td>
          
          <td class="center">
            <form method="post" asp-page-handler="SaveUser" id="save-changes-form">
              <input type="hidden" name="id" value="@user.Id"/>
              <input type="hidden" name="username" value="@user.UserName"/>
              <input type="hidden" name="role" value="@(UserManager.IsInRoleAsync(user, "Admin").Result ? "admin" : "user")"/>
              <input type="hidden" name="email" value="@user.Email"/>
              <input type="hidden" name="previousSearchQuery" value="@Model.UserSearchQuery" />
              <input type="hidden" name="previousEventSearchQuery" value="@Model.EventSearchQuery" />
              <input type="hidden" name="previousContactSearchQuery" value="@Model.ContactSearchQuery" />
              <button type="submit" class="material-symbols-outlined hidden" disabled>save</button>
            </form>
          </td>
        </tr>
      }
    </table>
  </div>
</div>