evently/Models/Event.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace evently.Models
{
    public class Event
    {
        public string Id { get; set; }

        [Required]
        public string Name { get; set; } = "";
        
        // Host of the event (User)
        [Required]
        public string HostId { get; set; }
        
        // Navigation property for the host
        // [Required] [ForeignKey("HostId")] public virtual User Host { get; set; }
        
        [Required]
        public string Description { get; set; } = "";
        
        [Required]
        public string ImageUrl { get; set; } = "";
        
        
        public string? VideoUrl { get; set; } = "";
        
        [Required]
        public string Location { get; set; } = "";
        
        [Required]
        public DateTime DateTime { get; set; } = DateTime.Now;
        
        [Required]
        public int Capacity { get; set; } = 0; // Total seats
        
        [Required]
        public int Registered { get; set; } = 0; // Seats filled
        
        [Required]
        public float Price { get; set; } = 0.0f; // Price per seat (in GBP)
    }
}

evently/Pages/Events/Bookings.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using evently.Models;

namespace evently.Pages.Events;

[Authorize(Policy = "CanEditEvent")]
public class Bookings : PageModel
{
    
    public readonly EventAppDbContext Db;
    
    public Event Event { get; set; }
    public List<EventBooking> EventBookings { get; set; }
    
    public Bookings(EventAppDbContext db)
    {
        this.Db = db;
    }
    
    public void OnGet(string id)
    {
        Event = Db.Events.FirstOrDefault(e => e.Id.ToString() == id);
        if (Event == null) return;
        
        EventBookings = Db.Bookings.Where(b => b.EventId == Event.Id).ToList();
        
    }
    
    public async Task<IActionResult> OnPostDeleteAsync(int bookingId)
    {
        var booking = await Db.Bookings.FindAsync(bookingId);
        if (booking == null) 
        {
            TempData["BannerMessage"] = "Booking not found!";
            return RedirectToPage();
        }

        Event? e = Db.Events.FirstOrDefault(e => e.Id == booking.EventId);
        if (e == null)
        {
            TempData["BannerMessage"] = "Event not found! Removing booking anyway.";
            Db.Bookings.Remove(booking);
            await Db.SaveChangesAsync();
            
            return RedirectToPage();
        }
        
        e.Registered -= booking.Tickets;
        Db.Bookings.Remove(booking);
        await Db.SaveChangesAsync();
        TempData["BannerMessage"] = "Booking deleted!";
        
        return RedirectToPage();
    }
}

evently/Pages/Events/Edit.cshtml.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using evently.Models;

namespace evently.Pages.Events;

[Authorize(Policy = "CanEditEvent")]
public class Edit : PageModel
{
    public readonly EventAppDbContext Db;
    private readonly UserManager<User> _userManager;


    [BindProperty(SupportsGet = true)]
    public string Id { get; set; } // Event ID
    
    [BindProperty]
    public Event? TheEvent { get; set; }
    
    public bool IsAdmin => User.IsInRole("Admin");
    public bool IsNew => TheEvent?.Id == "N/A";
    public bool IsEmailConfirmed = false;
    
    // [BindProperty]
    public string EventHostUsername { get; set; }

    public Edit(EventAppDbContext db, UserManager<User> userManager)
    {
        this.Db = db;
        _userManager = userManager;
    }
    
    public async Task<IActionResult> OnGetAsync()
    {
        string currentUserId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value ?? "";
        User? currentUser = Db.Users.FirstOrDefault(u => u.Id == currentUserId);
        if (currentUser == null) return RedirectToPage("/Account/Manage/Index", new {area = "Identity"});
        
        // Check if the user has confirmed their email
        IsEmailConfirmed = await _userManager.IsEmailConfirmedAsync(currentUser);
        if (!IsEmailConfirmed)
        {
            TempData["BannerMessage"] = "You must confirm your email before you can create or edit an event.";
            return RedirectToPage("/Account/Manage/Index", new {area = "Identity"});
        }
        
        // Making a new event
        if (string.IsNullOrEmpty(Id))
        {
            TheEvent = new Event
            {
                Id = "N/A", // ONPOST will check if the ID is "" and create a new GUID
                HostId = currentUserId
            };
            return Page();
        }
        
        
        TheEvent = Db.Events.FirstOrDefault(e => e.Id == Id);
        if (TheEvent == null) return RedirectToPage("/Events/Index");
        
        return Page();
    }
    
    public async Task<IActionResult> OnPost()
    {
        
        // TheEvent = await Db.Events.FindAsync(TheEvent.Id);
        // if (TheEvent == null) return RedirectToPage("/Events/Index");
        
        // Check that the host id is the same as the user id, or if the user is an admin
        if (TheEvent.HostId != User.FindFirst(ClaimTypes.NameIdentifier)?.Value && !User.IsInRole("Admin"))
        {
            TempData["BannerMessage"] = "You do not have permission to do that!";
            return RedirectToPage("/Events/View", new { id = TheEvent.Id });
        }
        
        Console.WriteLine("Stage 1" + Db.Entry(TheEvent).State); // Debugging
        
        // New event
        if (TheEvent.Id == "N/A")
        {
            User? host = Db.Users.FirstOrDefault(u => u.Id == TheEvent.HostId);
            if (host == null)
            {
                TempData["BannerMessage"] = "Host not found. Please double check the host ID.";
                return Page();
            }
            
            TheEvent.Id = Guid.NewGuid().ToString();
            Db.Events.Add(TheEvent);
            await Db.SaveChangesAsync();
            TempData["BannerMessage"] = "Event created successfully!";
            return RedirectToPage("/Events/View", new { id = TheEvent.Id });
        }
        
        if (!ModelState.IsValid)
        {
            // Print why the model is invalid
            foreach (var modelStateKey in ModelState.Keys)
            {
                var modelStateVal = ModelState[modelStateKey];
                foreach (var error in modelStateVal.Errors)
                {
                    Console.WriteLine(error.ErrorMessage);
                }
            }

            return Page();
        }
        
        if(TheEvent.Capacity < TheEvent.Registered)
        {
            TempData["BannerMessage"] = "Capacity cannot be less than the number of registered attendees!";
            return Page();
        }
        
        // Make sure they either own this event or are an admin
        if (TheEvent.HostId != User.FindFirst(ClaimTypes.NameIdentifier)?.Value && !User.IsInRole("Admin"))
        {
            TempData["BannerMessage"] = "You do not have permission to do that!";
            return RedirectToPage("/Events/View", new { id = TheEvent.Id });
        }
        Console.WriteLine("Stage 2" + Db.Entry(TheEvent).State); // Debugging
        
        Db.Events.Update(TheEvent);
        await Db.SaveChangesAsync();
        
        Console.WriteLine("Stage 3" + Db.Entry(TheEvent).State); // Debugging
        
        TempData["BannerMessage"] = "Event updated successfully!";
        return RedirectToPage("/Events/View", new { id = TheEvent.Id });
    }
}

evently/Pages/Events/View.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using evently.Models;

namespace evently.Pages.Events;

// [Authorize]
public class View : PageModel
{
    public Event Event { get; set; }
    public string EventHost { get; set; }
    
    [BindProperty(SupportsGet = true)]
    public FormInput Input { get; set; }
    
    [BindProperty]
    [StringLength(1500, ErrorMessage = "Message must be less than 1500 characters.")]
    public string ReviewMessage { get; set; }
    
    public List<ReviewWithUsername> Reviews { get; set; } = new List<ReviewWithUsername>();
    
    const int SUGGESTED_EVENT_COUNT = 4;
    
    public List<EventWithHost> SuggestedEvents { get; set; }
    
    public readonly EventAppDbContext Db;
    public readonly UserManager<User> UserManager;
    
    public View(EventAppDbContext db, UserManager<User> userManager)
    {
        this.Db = db;
        this.UserManager = userManager;
    }
    
    private void FetchReviews()
    {
        var _Reviews = Db.Reviews.Where(r => r.HostId == Event.HostId).ToList();
        foreach (var _review in _Reviews)
        {
            User? user = Db.Users.Find(_review.UserId);
            if (user == null) continue;
            ReviewWithUsername review = new ReviewWithUsername
            {
                Review = _review,
                Username = user.UserName ?? "Unknown"
            };
            Reviews.Add(review); 
        }
    }
    
    public IActionResult OnGet()
    {
        // This user
        User? user = Db.Users.Find(User.FindFirst(ClaimTypes.NameIdentifier)?.Value);
        if (user == null)
        {
            TempData["BannerMessage"] = "You must be logged in to view events.";
            return RedirectToPage("/Events/Index");
        }
        
        
        // Get the id from the URL:
        string? id = RouteData.Values["id"]?.ToString() ?? null;
        if (id == null) return RedirectToPage("/Events/Index"); 
        
        // Grab the event from the database
        Event? temp = Db.Events.FirstOrDefault(e => e.Id == id);
        if (temp != null) Event = temp;
        else return RedirectToPage("/Events/Index");
        
        // Grab the host's username from the database
        User? host = Db.Users.FirstOrDefault(u => u.Id == Event.HostId);
        if (host != null) EventHost = host.UserName ?? "Unknown";
        else return RedirectToPage("/Events/Index");
        
        // Set default values for the form
        Input = new FormInput
        {
            FirstName = user.FirstName ?? "",
            LastName = user.LastName ?? "",
            Email = User.FindFirst(ClaimTypes.Email)?.Value ?? "",
            Phone = user.PhoneNumber ?? "",
            TicketCount = 1,
            EventId = Event.Id,
        };
        
        // Get suggested events - START
        
        List<Event> LatestEvents = Db.Events.OrderBy(e => e.DateTime).Where(e => 
            e.DateTime > DateTime.Now &&
            e.HostId != user.Id &&
            e.Id != Event.Id
        ).Take(20).ToList();

        List<EventBooking> UserBookings = Db.Bookings.Where(b => b.UserId == user.Id).ToList();
        List<string> BookedHosts = new List<string>();
        List<string> BookedEventIds = new List<string>();
        foreach (EventBooking booking in UserBookings)
        {
            Event? e = Db.Events.FirstOrDefault(e => e.Id == booking.EventId);
            if (e != null && !BookedHosts.Contains(e.HostId)) BookedHosts.Add(e.HostId);
            if (e != null && !BookedEventIds.Contains(e.Id)) BookedEventIds.Add(e.Id);
        }
        
        List<Event> RelevantEvents = Db.Events.OrderBy(e => e.DateTime).Where(e => 
            e.DateTime > DateTime.Now &&
            e.Id != Event.Id &&
            e.HostId != user.Id &&
            BookedHosts.Contains(e.HostId) &&
            !BookedEventIds.Contains(e.Id)
        ).Take(4).ToList();
        
        List<Event> _SuggestedEvents = new List<Event>();
        _SuggestedEvents.AddRange(RelevantEvents);
        _SuggestedEvents.AddRange(LatestEvents);
        
        // Removes duplicates
        _SuggestedEvents = _SuggestedEvents.Distinct().ToList();
        
        SuggestedEvents = new List<EventWithHost>();
        foreach (Event e in _SuggestedEvents)
        {
            if(SuggestedEvents.Count >= SUGGESTED_EVENT_COUNT) break; // Take the first 4 events
            User thisHost = Db.Users.FirstOrDefault(u => u.Id == e.HostId);
            if (thisHost == null) continue;
            
            EventWithHost thisEventWithHost = new EventWithHost
            {
                Event = e,
                Host = thisHost
            };
            
            SuggestedEvents.Add(thisEventWithHost);
        }

        // Get suggested events - END
        
        FetchReviews();
        
        return Page();
    }
    
    public async Task<IActionResult> OnPostBookAsync() {
        
        // Url looks like: /Events/View/{id}
        // Get the id from the URL:
        string? id = RouteData.Values["id"]?.ToString() ?? null;
        if (id == null) return RedirectToPage("/Events/Index"); 
        
        // Grab the event from the database
        Event? temp = Db.Events.FirstOrDefault(e => e.Id == id);
        if (temp != null) Event = temp;
        else return NotFound("Event not found");

        try
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            Console.Out.WriteLine(Input.TicketCount);
            
            // Create a new booking
            EventBooking booking = new EventBooking
            {
                UserId = userId,
                EventId = Event.Id,
                Tickets = Input.TicketCount,
                TotalPrice = Input.TicketCount * Event.Price
            };

            // Add the booking to the database
            Db.Bookings.Add(booking);
            
            Event.Registered += Input.TicketCount;
            Db.Events.Update(Event);
            
            await Db.SaveChangesAsync();
            return RedirectToPage("/Account/Manage/Bookings/Index", new {area = "Identity"});
        } catch (Exception e)
        {
            return RedirectToPage("/Events/Index");
        }
    }
    
    public async Task<IActionResult> OnPostReviewAsync() {
        // Get the id from the URL:
        string? id = RouteData.Values["id"]?.ToString() ?? null;
        if (id == null) return RedirectToPage("/Events/Index");
        
        // Grab the event from the database
        Event? temp = Db.Events.FirstOrDefault(e => e.Id == id);
        if (temp != null) Event = temp;
        else return NotFound("Event not found");

        try
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            
            // Get the user:
            User? user = await Db.Users.FindAsync(userId);
            if (user == null) return RedirectToPage("/Events/Index");
            
            // Check their email is confirmed
            if (!await UserManager.IsEmailConfirmedAsync(user))
            {
                TempData["BannerMessage"] = "You must verify your email before submitting a review.";
                return RedirectToPage("/Events/View", new {id = Event.Id});
            }
            

            // Create a new review.
            var review = new EventReview
            {
                UserId = userId,
                HostId = Event.HostId,
                Message = ReviewMessage
            };

            // Add the review to the database
            Db.Reviews.Add(review);
            
            await Db.SaveChangesAsync();
            TempData["BannerMessage"] = "Review submitted successfully!";
            return RedirectToPage("/Events/View", new {id = Event.Id});
        } catch (Exception e)
        {
            Console.WriteLine("Review error: " + e);
            TempData["BannerMessage"] = "An error occurred while submitting your review.";
            return RedirectToPage("/Events/Index");
        }
    }

    public async Task<IActionResult> OnPostDeleteReviewAsync(int reviewId)
    {
        // Get the id from the URL:
        string? id = RouteData.Values["id"]?.ToString() ?? null;
        if (id == null) return RedirectToPage("/Events/Index");
        
        // Grab the event from the database
        Event? temp = Db.Events.FirstOrDefault(e => e.Id == id);
        if (temp != null) Event = temp;
        else return NotFound("Event not found");

        try
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            
            // Get the user:
            User? user = await Db.Users.FindAsync(userId);
            if (user == null) return RedirectToPage("/Events/Index");
            
            // Check their email is confirmed
            if (!await UserManager.IsEmailConfirmedAsync(user))
            {
                TempData["BannerMessage"] = "You must verify your email before deleting a review.";
                return RedirectToPage("/Events/View", new {id = Event.Id});
            }
            
            // Find the review
            EventReview? review = await Db.Reviews.FindAsync(reviewId);
            if (review == null) return RedirectToPage("/Events/View", new {id = Event.Id});
            
            // Check the user is the author of the review, or an admin
            if (review.UserId != userId && !await UserManager.IsInRoleAsync(user, "Admin")) return RedirectToPage("/Events/View", new {id = Event.Id});
            
            // Remove the review
            Db.Reviews.Remove(review);
            
            await Db.SaveChangesAsync();
            TempData["BannerMessage"] = "Review deleted successfully!";

evently/Pages/Events/Bookings.cshtml
@page "{id:maxlength(36)}"
@model evently.Pages.Events.Bookings

@{
    ViewData["Title"] = "Bookings";
}

@section Styles {
    <link rel="stylesheet" href="~/css/admin/index.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/events/bookings.css" asp-append-version="true" />
}

<h1>Bookings</h1>
<h3>@Model.Event.Name</h3>
<span>@Model.Event.Location @@ @Model.Event.DateTime.ToLongDateString() - @Model.Event.DateTime.ToShortTimeString()</span>

<div class="divider"></div>

@if (Model.EventBookings.Count == 0)
{
    <p>No bookings yet.</p>
}
else
{
    <table>
        <tr>
            <th>ID</th>
            <th>Username</th>
            <th>Tickets</th>
            <th class="center">Delete</th>
        </tr>
        @foreach (var booking in Model.EventBookings)
        {
            <tr>
                <td>@booking.Id</td>
                <td>@(Model.Db.Users.FirstOrDefault(u => u.Id == booking.UserId).UserName ?? "Unknown")</td>
                <td>@booking.Tickets</td>
                <td class="center">
                    <form method="post" asp-page-handler="delete">
                        <button type="submit" name="bookingId" value="@booking.Id" class="material-symbols-outlined hidden">delete</button>
                    </form>
                </td>
            </tr>
        }
    </table>
}

evently/Pages/Events/Index.cshtml
@page
@using evently.Models
@using Microsoft.AspNetCore.Identity
@model evently.Pages.Events.Index

@{
  ViewData["Title"] = "Events";
}

@section Styles {
  <link rel="stylesheet" href="~/css/events/list.css" />
  <link rel="stylesheet" href="~/css/events/event.css" />
}

@if (Model.query.Length > 0)
{
  <h1 style="margin-bottom: 0.1em;" id="title">Search results for @Model.query</h1>
  <h3 style="margin-top: 0;">Showing all results matching '@Model.query'</h3>
}
else
{
  <h1 style="margin-bottom: 0.1em;" id="title">Events</h1>
  <h3 style="margin-top: 0;">Showing all upcoming events</h3>
}

<div class="event-list">
  @foreach (var e in Model.Events)
  {
    <partial name="Events/_Event" model="e"/>
  }
</div>

<div class="bottom-fade"></div>

evently/Pages/Events/View.cshtml
@page "{id:maxLength(36)}" /* Requires that the URL contains the event ID (baseUrl/{id}) */
@using System.Globalization
@using Microsoft.AspNetCore.Identity
@using evently.Models
@model evently.Pages.Events.View

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

@{
  ViewData["Title"] = @Model.Event.Name;

  var seatsTotal = Model.Event.Capacity * 1f;
  var seatsFilled = Model.Event.Registered * 1f;

  string occupancy = "100%";
  if (Model.Event.Capacity > 0) occupancy = System.Math.Round(seatsFilled / seatsTotal, 2) * 100.0f + "%";

  User currentUser = await UserManager.GetUserAsync(User) ?? new User();
  bool isAdmin = await UserManager.IsInRoleAsync(currentUser, "Admin");
}

@section Styles {
  <link rel="stylesheet" href="~/css/events/view.css" asp-append-version="true" />
  <link rel="stylesheet" href="~/css/events/event.css" asp-append-version="true" />
}

<div class="header-container">
  <div>
    <h1 style="margin: 0" id="title">@Model.Event.Name</h1>
    <div class="host">
      <h3>Hosted By&nbsp;</h3>
      <h3 class="host-name">@Model.EventHost</h3>
    </div>
  </div>
  
  @* Only show header-icons-container if the user is an admin or is the host themselves *@
  @if (currentUser.Id == Model.Event.HostId || (await UserManager.IsInRoleAsync(currentUser, "Admin")))
  {
    <div class="header-icons-container">
      <a asp-page="/Events/Edit" asp-route-id="@Model.Event.Id" class="material-symbols-outlined">edit</a>
      <a asp-page="/Events/Bookings" asp-route-id="@Model.Event.Id" class="material-symbols-outlined">calendar_today</a>
    </div>
  }
  
  
</div>
<div class="divider"></div>

<section class="event-container">
  <div class="event-media-column">
    <section class="event-media-container desktop">
      <img class="event-media"/>
      <video class="event-media" controls></video>
      <span class="navigate-button material-symbols-outlined" id="prev">chevron_left</span>
      <span class="navigate-button material-symbols-outlined" id="next">chevron_right</span>
    </section>
    <section class="booking-form-container">
      <section>
        <h2>Booking Form</h2>
        <p class="booking-form-description">Please fill out the form below to book your place at this event.</p>
      </section>

      <div class="loader">
        <img src="/assets/loader.gif" alt="loading icon"/>
        <h3></h3>
        <span>Click to refresh page</span>
      </div>
      <form id="booking-form" method="post" asp-page-handler="book">
        <div class="form-input">
          <label for="fname">First Name</label>
          <input type="text" id="fname" placeholder="" readonly="readonly" asp-for="@Model.Input.FirstName" required>
        </div>
        <div class="form-input">
          <label for="lname">Last Name</label>
          <input type="text" id="lname" placeholder="" readonly="readonly" asp-for="@Model.Input.LastName" required>
        </div>
        <div class="form-input">
          <label for="email">Email</label>
          <input type="email" id="email" placeholder="name@domain.com" readonly="readonly" asp-for="@Model.Input.Email" required>
        </div>
        <div class="form-input">
          <label for="phone">Phone Number</label>
          <input type="tel" id="phone" placeholder="" readonly="readonly" asp-for="@Model.Input.Phone">
        </div>
        
        <div class="form-input">
          <label for="ticket-count">Tickets</label>
          <input type="number" id="ticket-count" placeholder="1" min="1" max="@(Model.Event.Capacity - Model.Event.Registered)" asp-for="@Model.Input.TicketCount" required>
        </div>
        
        @* <div class="g-recaptcha" data-sitekey="6LdcOyApAAAAADTPWLvEi0RMgb3CpEDD4AYqth6V" data-callback="onRecaptchaSubmit" data-expired-callback="onRecaptchaExpire"></div> *@
        <div class="booking-term">
          <input type="checkbox" id="terms" name="terms" required>
          <label for="terms">By checking this box I agree to pay <i><strong>@Model.EventHost</strong></i> the attendance fee (listed below*) upon arrival.</label>
        </div>
        <span class="captcha-warning">Please complete the reCaptcha before submitting this form.</span>
        <div class="divider faded"></div>
        <section class="total-book">
          <h3 class="event-price"><span>*</span></h3>
          <button class="book-button">BOOK NOW <span class="material-symbols-outlined">chevron_right</span></button>
        </section>
      </form>
    </section>
  </div>

  <div class="divider vertical"></div>

  <div class="event-details">
    <h2>Details</h2>
    <section class="event-stats">
      <div class="event-stat">
        <span class="material-symbols-outlined">calendar_month</span>
        <span class="event-stat-text" id="event-date">@Model.Event.DateTime.ToLongDateString() - @Model.Event.DateTime.ToShortTimeString()</span>
      </div>
      <div class="event-stat">
        <span id="seats-filled-icon" class="material-symbols-outlined">airline_seat_recline_extra</span>
        <span class="event-stat-text" id="event-seats">@occupancy</span>
      </div>
      <div class="event-stat">
        <span class="material-symbols-outlined">location_on</span>
        <span class="event-stat-text" id="event-location">@Model.Event.Location</span>
      </div>
    </section>
    <div class="divider faded"></div>

    <p class="event-description">@Model.Event.Description</p>
  </div>
  <section class="event-media-container mobile">
    <img class="event-media" alt="event image"/>
    <video class="event-media" controls></video>
    <span class="navigate-button material-symbols-outlined" id="prev">chevron_left</span>
    <span class="navigate-button material-symbols-outlined" id="next">chevron_right</span>
  </section>
</section>


<div class="review-container">
  <h2 style="margin-bottom: 0">Reviews</h2>
  <h3>Leave a review of this host</h3>
  <form method="post" asp-page-handler="Review">
    <div class="form-input">
      <span asp-validation-for="ReviewMessage" class="validation"></span>
      <textarea type="text" asp-for="ReviewMessage" placeholder="Start typing here..." required></textarea>
    </div>
    <section class="send-container">
      <button class="send-button">SEND REVIEW <span class="material-symbols-outlined">chevron_right</span></button>
    </section>
  </form>
  
  @foreach(var review in Model.Reviews) {
    <div class="review">
      <div class="review-header">
        <h3>@review.Username</h3>
        @if (currentUser.Id == review.Review.UserId || isAdmin)
        {
          <form asp-page-handler="DeleteReview">
            <input type="hidden" name="reviewId" value="@review.Review.Id"/>
            <button type="submit" class="material-symbols-outlined hidden">delete</button>
          </form> 
        }
      </div>
        <p>@review.Review.Message</p>
      </div>
  }
  
  <div class="divider faded"></div>
</div>

<h2 class="event-list-title">More Events</h2>
<h3>Based on your existing bookings and latest events</h3>
<div class="event-list">
  @foreach (var e in Model.SuggestedEvents) {
    <partial name="Events/_Event" model="e"/>
  }
</div>

@section Scripts
{
  <script>
    $(() => {
      function formatEventDisplay() {
        const full = @Model.Event.Registered >= @Model.Event.Capacity;
        
        const past = "@(Model.Event.DateTime < DateTime.Now)" == "True";
        const bookingFormDescription = $(".booking-form-description");
        if(full || past) {
          $("#booking-form").addClass("disabled");
          $("#booking-form > .booking-term > input").prop("disabled", true);
          $("#booking-form > .form-input > input").prop("readonly", true);
          $("#booking-form > .g-recaptcha").addClass("disabled");
          $(".book-button").prop("disabled", true);
        }
        if(past) {
          $(bookingFormDescription).text("Sorry, this event has already passed.");
          $(bookingFormDescription).addClass("full");
          $(".event-description").prepend('<strong style="color: var(--urgent)">Please note: This event has already passed and is no longer taking attendees.</strong><br><br>');
        }
        // Only allow one of the two messages to be displayed. Prioritise past events.
        else if (full) {
          $(bookingFormDescription).text("Sorry, this event is now at full capacity.");
          $(bookingFormDescription).addClass("full");
          $(".event-description").prepend('<strong style="color: var(--urgent)">Please note: This event is now full and is not taking any more attendees.</strong><br><br>');
        }
      }
      
      function initMediaPlayer() {
        const videoElem = $(".event-media-container > video");
        const imgElem = $(".event-media-container > img");

        imgElem.prop("src", "@Model.Event.ImageUrl");
        
        
        if (@(Model.Event.VideoUrl == null ? 1 : 0)) $(navigateButton).hide();
        else videoElem.prop("src", "@Model.Event.VideoUrl");
        // if(@Model.Event.VideoUrl == null || @Model.Event.VideoUrl?.Length <= 0) $(navigateButton).hide();
        // else videoElem.prop("src", "@Model.Event.VideoUrl");
        
        videoElem.hide();
      }
      
      function refreshTotal(){
        const ticketCount = $(ticketCounter).val();
        
        const price = Number.parseFloat(@Model.Event.Price);
        $(".event-price").text("£" + (price * ticketCount).toFixed(2));
      }
      
      const ticketCounter = $("#ticket-count");
      const navigateButton = $(".navigate-button");
      let showingVideo = false;
      formatEventDisplay();
      initMediaPlayer();
      refreshTotal();
      
      $(navigateButton).on("click", () => {
        showingVideo = !showingVideo;
        if(showingVideo){
          $(".event-media-container > img").fadeOut(500);
          $(".event-media-container > video").fadeIn(500);
        }
        else{
          $(".event-media-container > video").fadeOut(500);
          $(".event-media-container > img").fadeIn(500);
        }
      });
      
      $(ticketCounter).on("change", () => {
        refreshTotal();
      });
      
      $("#booking-form").on("submit", (e) => {
        $("#booking-form").hide();
        $(".loader").css("display", "flex");
        $(".loader > h3").text("Booking your spot...");
        $(".loader > span").hide();
        $(".loader").hide();
        $(".loader").slideDown(800);
      });
    })
  </script>
}